name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch: { }

jobs:
  publish:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu

      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish to GitHub Packages
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}